### PR TITLE
Gitlab CI

### PR DESCRIPTION
**Pull request by Gisleburt**
Depends on apolitical/platform-secrets#40

### CODE REVIEW

**Comment by Gisleburt** [comment]
* Doc tests will only run on things that are public too.

**Comment by Floppy** [comment]
The documentation deployment, btw, is very similar to the setup for the `docs` repo.

**Comment by Gisleburt** [comment]
I've not been able to get docs working. Any thoughts @Floppy?

https://engineering.beta.apolitical.co/docs/articles-api/

**Comment by Gisleburt** [comment]
Can we merge this and we'll add broken docs as an issue?

**Pull request merged**
